language: node_js
node_js:
   - "4.2"

# Google Chrome
#
# https://github.com/MrOrz/SeeSS/blob/master/.travis.yml
# https://github.com/travis-ci/travis-ci/issues/272#issuecomment-14402117
# http://stackoverflow.com/questions/19255976/how-to-make-travis-execute-angular-tests-on-chrome-please-set-env-variable-chr
#
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: npm run test-travis
